// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA82zAsbb0VsaYd_SXaHVPB0Gg72cbeHQE',
    appId: '1:787491011636:web:9ef69e8b5db8fecee49e61',
    messagingSenderId: '787491011636',
    projectId: 'fir-test-5e156',
    authDomain: 'fir-test-5e156.firebaseapp.com',
    storageBucket: 'fir-test-5e156.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwfoZe-qgYJp2CN-8P3omra6SST_UsePA',
    appId: '1:787491011636:android:f744b422bc2a22b5e49e61',
    messagingSenderId: '787491011636',
    projectId: 'fir-test-5e156',
    storageBucket: 'fir-test-5e156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNqzVEaaUxnHjq3nAuqE7Ozq7R3PvYnqw',
    appId: '1:787491011636:ios:12be4580ffee001be49e61',
    messagingSenderId: '787491011636',
    projectId: 'fir-test-5e156',
    storageBucket: 'fir-test-5e156.appspot.com',
    iosClientId: '787491011636-g4lplm9ofr3d93oov8tc1vvg1lbtqbqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
